Swift 5 and Xcode 10.2 support
RxSwiftCommunity/RxRealm pull request #123
Opened 2019-04-09 12:18 UTC by rynecheow

Signed-off-by: Ryne Cheow <rynecheow@gmail.com>

2019-04-09 12:21 UTC, freak4pc commented
Hey - RxSwift 5 is coming in a bit, let’s wait for that before putting this PR together

2019-04-30 12:07 UTC, lukas1 commented
RxSwift 5 has been released :-)

2019-04-30 13:30 UTC, rynecheow commented
Ready for review @icanzilb @freak4pc :)

2019-05-03 07:49 UTC, rynecheow commented
Ready for review @icanzilb @freak4pc :)

2019-05-03 09:31 UTC, freak4pc requested changes
Looks great overall! A few minor notes. I'd also like @icanzilb to review if he has the time.

2019-05-03 09:31 UTC, freak4pc commented on Example/RxRealm/AppDelegate.swift
> +import UIKit
Why did you swap those? Not a huge deal but usually it's system-frameworks-first and then 3rd party.

2019-05-03 09:31 UTC, freak4pc commented on RxRealm.podspec
> +  s.version          = "0.8.0"
This should be a major version bump

2019-05-03 09:31 UTC, freak4pc commented on Pod/Classes/RxRealm.swift
> +                onError?(nil, RxRealmError.unknown)
If this is aligned this way I think you should align the `var` and `let`s to the first (`let element`)

2019-05-04 00:53 UTC, rynecheow commented
Ready for another review @freak4pc

2019-05-04 09:56 UTC, freak4pc approved these changes
Looks good to me. Let's give @icanzilb until Monday to give this another pass. If not, I'll merge as is.

2019-05-06 12:07 UTC, rynecheow commented
Sure @freak4pc :)

2019-05-07 00:30 UTC, rynecheow commented
Are we ready to merge this?

2019-05-07 11:12 UTC, icanzilb commented
I’m on vacation and the PR seems too big to review on my phone. As long as the test suite passes and the example apps (both iOS and macOS) behave as before I’m good with merging

2019-05-07 12:54 UTC, rynecheow commented
Thanks @icanzilb! @freak4pc Would need your help to merge the PR as I can't be merging my own if all's good!

2019-05-07 12:59 UTC, freak4pc commented
@rynecheow At home right now, I'll run it locally at night and let you know. Thanks :)

2019-05-08 11:15 UTC, freak4pc approved these changes

2019-05-08 11:15 UTC, freak4pc commented on Cartfile.resolved
> +github "ReactiveX/RxSwift" "5.0.0"
This should resolve to 5.0.1. 
5.0.0 is static.

2019-05-08 11:16 UTC, merged