Move to realm 5
RxSwiftCommunity/RxRealm pull request #143
Opened 2020-05-22 11:01 UTC by MortyMerr

2020-05-22 18:10 UTC, Loupehope commented on Example/RxRealm_Tests/RxRealmOnQueueTests.swift
> +              }
indent

2020-05-22 18:18 UTC, Loupehope commented on Example/RxRealm_Tests/RxRealmOnQueueTests.swift
> +              }
indent

2020-05-22 20:17 UTC, Loupehope requested changes

2020-05-22 20:17 UTC, Loupehope commented on Example/RxRealm_Tests/RxRealmOnQueueTests.swift
> +              }
indent

2020-05-22 20:17 UTC, Loupehope commented on Example/RxRealm_Tests/RxRealmOnQueueTests.swift
> +              }
indent

2020-05-23 08:25 UTC, kaminisea approved these changes
I have confirmed the following.
- Versioning
- Can it be built?
- Are the tests correct?

I don't see a problem with any of them 👍

2020-05-23 10:40 UTC, rynecheow approved these changes
LGTM. We should fix the indentation inconsistency - otherwise am good with the rest, did not see much breaking change for RxRealm here.

2020-05-26 03:42 UTC, muukii reviewed
I've added the suggestion to fix the indent issue.

2020-05-26 03:42 UTC, muukii commented on Example/RxRealm_Tests/RxRealmOnQueueTests.swift
> +              }
```suggestion
                realm.add(UniqueObject(2))
            }
```

2020-05-26 03:42 UTC, muukii commented on Example/RxRealm_Tests/RxRealmOnQueueTests.swift
> +              }
```suggestion
                realm.add(UniqueObject(2))
            }
```

2020-05-26 03:44 UTC, muukii commented
@rynecheow 
Hi,
I put the suggestion that fixes the indent issue from GitHub review.
We can ship the version that supports Realm 5, if we could commit this fixed from here.

2020-05-27 10:31 UTC, MortyMerr commented on Example/RxRealm_Tests/RxRealmOnQueueTests.swift
> +              }
Fixed

2020-05-27 10:31 UTC, MortyMerr commented on Example/RxRealm_Tests/RxRealmOnQueueTests.swift
> +              }
Thanks, fixed

2020-05-27 10:34 UTC, MortyMerr commented
Hey @muukii @catelina777 @Loupehope thank you so much for fast answers! And sorry for my long fixes. There was a threading issue with tests and I didn't have time to dig into it.
I fixed indents and clean up tests. Could u please approve it again? Thanks.

BTW, really important question: if `synchronousStart: true`, should we dispatch the first item on provided notifications queue? Or it should be dispatched on the current thread?

2020-05-28 06:22 UTC, muukii commented
@MortyMerr 

> BTW, really important question: if synchronousStart: true, should we dispatch the first item on provided notifications queue? Or it should be dispatched on the current thread?

It seems the current implementation would be good, but there are some chances that causes an exception for using incorrect thread?

I think, `synchronousStart` means we can get the current item immediately that dispatches current stack.
So If it dispatches on notification queue, in some case we can't get the first item synchronously.

If the parameter name was `emitsCurrentValue`, we could understand it emits the value on the specified queue.

2020-05-28 06:40 UTC, muukii commented
> but there are some chances that cause an exception for using incorrect thread?

I thought the exception might not happen.
Because the first one will be for the thread that started observation and the received item would be for the thread that the queue uses.

However, Since this behavior, the developers take mistakes using thread in receiving item closure.

```swift
Observable...(queue: .somethingQueue) // somethingQueue uses Thread 1 as an example
  .subscribe(onNext: { element in
    // first time - element for Thread 0

    // second time - element for Thread 1
 })
```

So, My suggestion, when set the syncronousStart flag, make the specifying queue disabled.
Let me know if I wrong understanding.
Thanks.

2020-05-28 11:40 UTC, icanzilb commented
Here's my 2c and a little of background info to help you decide how to solve this issue.

`synchronousStart` was added because realm notifications are by default asynchronous and so sometimes when you bound a table view or some labels on screen you would have a little flash when the view controller appears with empty controls for a moment and then in a split second the first realm notification would kick in and the controls will update with the initial values.

I'm not so sure if in reality there is another use case outside of binding UI controls but maybe there is ...

In any case I personally would expect with or without synchronous start that the API will respect the queue parameter and emit on that queue.

2020-05-29 08:41 UTC, MortyMerr commented
Yeah, I also can imagine only this case for `synchronousStart`. I don't think it should emit initial value on provided queue, because it will bring this "little flash" back

2020-06-04 10:08 UTC, merged